# Site wide configuration

title: "LearningNerd"
description: "Learning everything, sharing everything I learn!"
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url: http://learningnerd.com

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
repository: learningnerd/learningnerd.github.com

# Front Matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files that are posts
      type: "posts"
    values:
      ads: true
      comments: true

# Site owner
owner:
  name: "Liz Krane"
  email:
  twitter: "LearningNerd"
  google:
    ad-client: "ca-pub-3989977449236900"
    ad-slot: "4864146471"
  bio: "Liz is a full-time nerd, sharing everything she learns as she tries to learn everything!"
  avatar: "/lizkrane.jpg"
  disqus-shortname: "learningnerd"


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
